version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_cadpog
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cadpog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
